name: Verificar Build do Site 🤖

# O que ativa o robô? (Gatilho)
on:
  pull_request:
    branches: [main] # Só roda quando você tentar mandar algo para a main

jobs:
  testar-codigo:
    runs-on: ubuntu-latest # O robô vai usar um computador Linux (Ubuntu)

    steps:
      # Passo 1: O robô entra na sua pasta do GitHub
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      # Passo 2: O robô instala o Node.js (como você fez no seu PC)
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Passo 3: O robô instala as bibliotecas (npm install)
      - name: Instalar dependências
        run: npm install

      # Passo 4: O robô tenta buildar o projeto (A hora da verdade!)
      - name: Executar Build do Next.js
        run: npm run build
        env:
          # Precisamos passar a variável do Cloudinary para o robô não dar erro
          NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}