name: Verificar Build do Site 🤖

on:
  pull_request:
    branches: [main]

jobs:
  testar-codigo:
    runs-on: ubuntu-latest
    
    # Aqui ativamos a variável que o GitHub sugeriu para usar o Node 24 agora
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4 # A v4 já suporta o Node 24 se forçado

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Atualizamos a versão do Node para a 24
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Executar Build do Next.js
        run: npm run build
        env:
          NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}